import os
import math
from PIL import Image

output_dir = 'public/frames-webp'
os.makedirs(output_dir, exist_ok=True)

# Image path generated by agent
img_path = r'C:\Users\PC\.gemini\antigravity\brain\f4f2c59f-34a8-45ae-b71d-aeb57cbf57ca\brutalist_vault_panoramic_1776721246572.png'

print("Loading base image...")
base_img = Image.open(img_path).convert('RGB')
w, h = base_img.size

num_frames = 200
target_w = 1920
target_h = 1080

# The source image is panoramic. We want to extract a 16:9 crop that slowly pans from left to right, and slightly zooms in.
crop_w = int(h * 16 / 9)
crop_h = h

if crop_w > w:
    crop_w = w
    crop_h = int(w * 9 / 16)

start_x = 0
end_x = w - crop_w

start_zoom = 1.0
end_zoom = 1.15 # 15% zoom in over the course

print(f"Generating {num_frames} frames...")
for i in range(num_frames):
    progress = i / max(1, (num_frames - 1))
    
    # Easing function for smooth pan
    ease = progress * progress * (3 - 2 * progress) # smoothstep
    
    current_x = int(start_x + (end_x - start_x) * ease)
    current_zoom = start_zoom + (end_zoom - start_zoom) * ease
    
    # Calculate zoomed crop dimensions
    z_w = int(crop_w / current_zoom)
    z_h = int(crop_h / current_zoom)
    
    # Calculate top/left to keep centered vertically
    z_x = current_x + (crop_w - z_w) // 2
    z_y = (h - z_h) // 2
    
    # Crop and resize
    frame = base_img.crop((z_x, z_y, z_x + z_w, z_y + z_h))
    frame = frame.resize((target_w, target_h), Image.Resampling.LANCZOS)
    
    # Save as webp
    filename = f"frame_{(i+1):06d}.webp"
    frame.save(os.path.join(output_dir, filename), 'WEBP', quality=85)
    
    if i % 20 == 0:
        print(f"Generated {i}/{num_frames}...")

print("Done! Frames are in public/frames-webp")
